In [148]:
import pandas as pd
path="C:\\Users\\akash\\Downloads\\assign_chubb_engineering  (1).json"
df= pd.read_json(path)
df.head()

,altran technologies india pvt ltd,L&T Technology Services Ltd.,Amdocs,Xperia,Ultra-Scan Corporation,Adani Gas,Benecke-Kaliko,Graphene Semiconductors,Mercedes-Benz Research and Development India,Ceat Tyres Limited,...,eteva consulting pvt. ltd.,"iete - vce, hyderabad chapter",apl mechanical services limited,Absolute Web,e bliss technology,babu it jobs,capital honda service centre,systems plus llc,gemini traze rfid pvt ltd,radiate e-services pvt. ltd.
company_uuid,None,,fbd567c5e7395b46974ece634a19ff2e,7aa9a32dd8f27a05646e7317af05959b,,,91e555fc156c5d89bbe7ff742fe3adac,,c25f1a3fa62b18801afcc4bf7c1e3c4e,bedb8e58ae1201a784d7f7b1a63d2ccc,...,,,None,,,None,,,,
companies_they_hire_from,{'company_name': {'L&T Technology Services Ltd...,{'company_name': {'HCL Technologies': {'count'...,{'company_name': {'Tata Consultancy Services':...,{'company_name': {'Ultra-Scan Corporation': {'...,{'company_name': {'Wipro Technologies': {'coun...,{'company_name': {'Wonderware Scandinavia': {'...,{'company_name': {'Tata Consultancy Services':...,{'company_name': {'L&T Technology Services Ltd...,{'company_name': {'Tata Consultancy Services':...,"{'company_name': {'Accenture': {'count': 3, 'd...",...,"{'company_name': {}, 'count': 0}","{'company_name': {}, 'count': 0}",{'company_name': {'Tech Mahindra': {'count': 1...,"{'company_name': {}, 'count': 0}","{'company_name': {}, 'count': 0}",{'company_name': {'Tech Mahindra': {'count': 1...,"{'company_name': {}, 'count': 0}","{'company_name': {}, 'count': 0}","{'company_name': {}, 'count': 0}","{'company_name': {}, 'count': 0}"
employees,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 4, 'freshers_count': 0, 'freshers_uu...","{'count': 173, 'freshers_count': 2, 'freshers_...","{'count': 3, 'freshers_count': 0, 'freshers_uu...","{'count': 384, 'freshers_count': 0, 'freshers_...","{'count': 5, 'freshers_count': 1, 'freshers_uu...",...,"{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu..."
companies_where_their_ex_employees_work,"{'count': 0, 'company_name': {}}","{'count': 2192, 'company_name': {'Robert Bosch...","{'count': 733, 'company_name': {'Tata Consulta...","{'count': 1, 'company_name': {'Cisco': {'count...","{'count': 246, 'company_name': {'Qualcomm': {'...","{'count': 3, 'company_name': {'L&T Technology ...","{'count': 112, 'company_name': {'Harman Intern...","{'count': 37, 'company_name': {'L&T Technology...","{'count': 103, 'company_name': {'Capgemini': {...","{'count': 2, 'company_name': {'L&T Technology ...",...,"{'count': 1, 'company_name': {'Volga Infotech'...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 0, 'company_name': {}}","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 0, 'company_name': {}}","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':..."
is_score_calculated,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [149]:
df.tail()

,altran technologies india pvt ltd,L&T Technology Services Ltd.,Amdocs,Xperia,Ultra-Scan Corporation,Adani Gas,Benecke-Kaliko,Graphene Semiconductors,Mercedes-Benz Research and Development India,Ceat Tyres Limited,...,eteva consulting pvt. ltd.,"iete - vce, hyderabad chapter",apl mechanical services limited,Absolute Web,e bliss technology,babu it jobs,capital honda service centre,systems plus llc,gemini traze rfid pvt ltd,radiate e-services pvt. ltd.
employees,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 4, 'freshers_count': 0, 'freshers_uu...","{'count': 173, 'freshers_count': 2, 'freshers_...","{'count': 3, 'freshers_count': 0, 'freshers_uu...","{'count': 384, 'freshers_count': 0, 'freshers_...","{'count': 5, 'freshers_count': 1, 'freshers_uu...",...,"{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'freshers_count': 0, 'freshers_uu..."
companies_where_their_ex_employees_work,"{'count': 0, 'company_name': {}}","{'count': 2192, 'company_name': {'Robert Bosch...","{'count': 733, 'company_name': {'Tata Consulta...","{'count': 1, 'company_name': {'Cisco': {'count...","{'count': 246, 'company_name': {'Qualcomm': {'...","{'count': 3, 'company_name': {'L&T Technology ...","{'count': 112, 'company_name': {'Harman Intern...","{'count': 37, 'company_name': {'L&T Technology...","{'count': 103, 'company_name': {'Capgemini': {...","{'count': 2, 'company_name': {'L&T Technology ...",...,"{'count': 1, 'company_name': {'Volga Infotech'...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 0, 'company_name': {}}","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 0, 'company_name': {}}","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':...","{'count': 1, 'company_name': {'Tech Mahindra':..."
is_score_calculated,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Department_Tier-1_College_Density_Score,0.00001,0.004499,0.00526,0.00001,0.07193,0.00001,0.00578,0.00001,0.015625,0.00001,...,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001
Department_Tier-1_College_Freshers_Density_Score,0.00001,0.00464,0.035714,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,...,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001,0.00001

In [150]:
df.size

420882

In [151]:
df.columns

Index(['altran technologies india pvt ltd', 'L&T Technology Services Ltd.',
       'Amdocs', 'Xperia', 'Ultra-Scan Corporation', 'Adani Gas',
       'Benecke-Kaliko', 'Graphene Semiconductors',
       'Mercedes-Benz Research and Development India', 'Ceat Tyres Limited',
       ...
       'eteva consulting pvt. ltd.', 'iete - vce, hyderabad chapter',
       'apl mechanical services limited', 'Absolute Web', 'e bliss technology',
       'babu it jobs', 'capital honda service centre', 'systems plus llc',
       'gemini traze rfid pvt ltd', 'radiate e-services pvt. ltd.'],
      dtype='object', length=60126)

In [152]:
df1=df.transpose()
df1.head()

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score
altran technologies india pvt ltd,None,{'company_name': {'L&T Technology Services Ltd...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001
L&T Technology Services Ltd.,,{'company_name': {'HCL Technologies': {'count'...,"{'count': 6890, 'freshers_count': 2155, 'fresh...","{'count': 2192, 'company_name': {'Robert Bosch...",True,0.004499,0.00464
Amdocs,fbd567c5e7395b46974ece634a19ff2e,{'company_name': {'Tata Consultancy Services':...,"{'count': 1711, 'freshers_count': 28, 'fresher...","{'count': 733, 'company_name': {'Tata Consulta...",False,0.00526,0.035714
Xperia,7aa9a32dd8f27a05646e7317af05959b,{'company_name': {'Ultra-Scan Corporation': {'...,"{'count': 6, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Cisco': {'count...",False,0.00001,0.00001
Ultra-Scan Corporation,,{'company_name': {'Wipro Technologies': {'coun...,"{'count': 1140, 'freshers_count': 8, 'freshers...","{'count': 246, 'company_name': {'Qualcomm': {'...",False,0.07193,0.00001

In [153]:
print(len(df1))
df1.columns

60126

Index(['company_uuid', 'companies_they_hire_from', 'employees',
       'companies_where_their_ex_employees_work', 'is_score_calculated',
       'Department_Tier-1_College_Density_Score',
       'Department_Tier-1_College_Freshers_Density_Score'],
      dtype='object')

In [154]:
df1.tail()

,company_uuid,companies_they_hire_from,employees,companies_where_their_ex_employees_work,is_score_calculated,Department_Tier-1_College_Density_Score,Department_Tier-1_College_Freshers_Density_Score
babu it jobs,None,{'company_name': {'Tech Mahindra': {'count': 1...,"{'count': 1, 'freshers_count': 0, 'freshers_uu...","{'count': 0, 'company_name': {}}",False,0.00001,0.00001
capital honda service centre,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001
systems plus llc,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001
gemini traze rfid pvt ltd,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001
radiate e-services pvt. ltd.,,"{'company_name': {}, 'count': 0}","{'count': 0, 'freshers_count': 0, 'freshers_uu...","{'count': 1, 'company_name': {'Tech Mahindra':...",False,0.00001,0.00001

In [155]:
df1['companies_they_hire_from']  #Length: 60126

altran technologies india pvt ltd    {'company_name': {'L&T Technology Services Ltd...
L&T Technology Services Ltd.         {'company_name': {'HCL Technologies': {'count'...
Amdocs                               {'company_name': {'Tata Consultancy Services':...
Xperia                               {'company_name': {'Ultra-Scan Corporation': {'...
Ultra-Scan Corporation               {'company_name': {'Wipro Technologies': {'coun...
                                                           ...
babu it jobs                         {'company_name': {'Tech Mahindra': {'count': 1...
capital honda service centre                          {'company_name': {}, 'count': 0}
systems plus llc                                      {'company_name': {}, 'count': 0}
gemini traze rfid pvt ltd                             {'company_name': {}, 'count': 0}
radiate e-services pvt. ltd.                          {'company_name': {}, 'count': 0}
Name: companies_they_hire_from, Length: 60126, dtype: object

In [156]:
#  List of companies they hired from
import numpy as np
companies_they_hire_from_new=[]
for i in range(60126):
    companies_they_hire_from_new.append(list(df1['companies_they_hire_from'][i]['company_name'].keys()))
    
# So we get the list of companies from with each companies hire individually
for i in range(60126):
    if len(companies_they_hire_from_new[i])==0:
        companies_they_hire_from_new[i]=np.nan

In [157]:
companies_they_hire_from_new[60122]

nan

In [158]:
# Employee count they hired
count=[]
for i in range(60126):
    sum=0
    x_count=len(list(df1['companies_they_hire_from'][i]['company_name'].values()))
    for items in range(x_count):
        y=list(df1['companies_they_hire_from'][i]['company_name'].values())[items]['count']
        sum=sum+y
    count.append(sum)
count[100]

31

In [159]:
df1['employees'].isnull().sum()
#so we can find that the column has no null values in any of the row 
#now we can proceed with the output

0

In [160]:
####                                     Employees Count
employees_count=[]
for i in range(60126):
    employees_count.append(df1['employees'][i]['count'])
employees_count[10:20]

[26, 2, 5, 216, 0, 21317, 0, 5, 19, 0]

In [161]:
df1['employees'][10]['from_iit']

{'count': 0, 'employees_uuid': [], 'freshers_count': 0, 'freshers_uuid': []}

In [162]:
#                                     IIT COUNT
#                                     IIT FRESHER COUNT 
iit_count=[]
iit_fresher_count=[]
for i in range(60126):
    iit_count.append(df1['employees'][i]['from_iit']['count'])
    iit_fresher_count.append(df1['employees'][i]['from_iit']['freshers_count'])
print(iit_fresher_count[3:8])
iit_count[3:8]

[0, 0, 0, 0, 0]

[0, 63, 0, 1, 0]

In [163]:
df1['employees'][3000]['from_nit']

{'count': 0, 'employees_uuid': [], 'freshers_count': 0, 'freshers_uuid': []}

In [164]:
nit_count=[]
nit_fresher_count=[]
for i in range(60126):
    nit_count.append(df1['employees'][i]['from_nit']['count'])
    nit_fresher_count.append(df1['employees'][i]['from_nit']['freshers_count'])
print(nit_fresher_count[3:8])
nit_count[3:8]

[0, 0, 0, 0, 0]

[0, 17, 0, 0, 0]

In [165]:
print(df1["companies_where_their_ex_employees_work"].isnull().sum())
len(df1["companies_where_their_ex_employees_work"])

0

60126

In [166]:
#                                     companies_their_ex_employees_work
companies_their_ex_employees_work=[]
for i in range(60126):
    companies_their_ex_employees_work.append(list(df1["companies_where_their_ex_employees_work"][i]['company_name'].keys()))
for i in range(60126):
    if len(companies_their_ex_employees_work[i])==0:
        companies_their_ex_employees_work[i]=np.nan
companies_their_ex_employees_work[2:5]

[['Tata Consultancy Services',
  'Accenture',
  'Tech Mahindra',
  'BigMachines',
  'Wipro Technologies',
  'Barclays',
  'Mastercard Loyalty Solutions Australia',
  'BNY Mellon',
  'Cognizant',
  'IBM',
  'Infosys',
  'Mphasis',
  'L&T Infotech',
  'NetCracker Technology',
  'PRM Cloud Solutions',
  'Ciena',
  'Virtusa',
  'MindTree',
  'Nagarro',
  'NICE Systems',
  'HCL Technologies',
  'UnitedHealth Group',
  'Citibank India',
  'Capgemini',
  'Globant',
  'Ericsson Ventures',
  'John Deere Brazil',
  'Legato Health Technologies',
  'FIS',
  'Harman International Industries',
  'Impetus Technologies',
  'Teradata UK',
  'Telus International',
  'UBS Delta',
  'The Royal Bank Of Scotland Private Limited Company',
  'Fiserv',
  'Microsoft',
  'Signus Labs',
  'Publicis Sapient',
  'Actimize',
  'Siemens Technology India',
  'UKG',
  'TomTom',
  'Altimetrik Corp.',
  'Bank of America',
  'Syntel',
  'Orange Business Services',
  'BT',
  'EY Startup Challenge',
  'Cisco',
  'American Express',
  'volkswagen it services india pvt. ltd.',
  'Belafonte TACOLCY',
  'Amazon',
  'Hexaware Technologies',
  'L&T Technology Services Ltd.',
  'Telstra Media',
  'Aera Technology',
  'Sas Company Store',
  'Extentia Information Technology',
  'Hitachi Consulting',
  'GlobalLogic',
  'Cybage Software',
  'Clarice Technologies',
  'Incedo Inc.',
  'Symantec Cybersecurity Services',
  'Michelin',
  'Nuance Communications',
  'Turbot',
  'Thales Group',
  'Accolite Digital',
  'barclays wealth management',
  'Varian',
  'SunGard',
  'iNautix',
  'Broadridge',
  'Brillio',
  'Optum Frontier Therapies',
  'Morgan Stanley',
  'TSYS',
  'Tata Communications',
  'Xoriant',
  'AppDirect',
  'TIBCO',
  'PayPal',
  'Icertis',
  'Barclays Investment Bank',
  'Landmark Group',
  'Optum Global Solutions',
  'SIXT Research & Development India',
  'Walmart Global Tech India',
  'Qvantel',
  'Visa',
  'Vodafone Italy',
  'Monocept',
  'John Deere',
  'YASH Technologies',
  'IHS Markit',
  'Wells Fargo Financial',
  'Credit Suisse Securities Canada',
  'Apple',
  'bmc software india privatelimited',
  'Guardian Life',
  'Nokia',
  'Capita Customer Mgt',
  'GS Lab',
  'InfoBeans Technologies Limited',
  'Cerence',
  'prairieFyre Software',
  'IQVIA',
  'Fidelity National Financial',
  '6sense',
  'Pfizer',
  'Walmart Global Tech',
  'l&t-nxt',
  'citicorp citibank',
  'Invesco',
  'Principal Financial Group',
  'capita india private limited',
  'OLAM International',
  'Airtel Payments Bank',
  'GNet',
  'Jago',
  'RSA Security',
  'schlumberger india technology centre private limited',
  'Deutsche Bank',
  'Paytm Payments Bank',
  'Aurea Software',
  'Red Hat',
  'ZS Associates',
  'VeriSign',
  'JP Morgan Chase',
  'Dassault Systemes Solutions Lab',
  'Bank of Maharashtra',
  'Genpact Headstrong Capital Markets',
  'Bureau Veritas Consumer Products Services',
  'Eaton',
  'Xavient Information Systems',
  'Continuum Managed Services',
  'Rackspace Technology',
  'TOSHIBA',
  'Giesecke+Devrient',
  'Bizita Technologies',
  'InQuira',
  'One Network Enterprises',
  'OnlineSales.ai',
  'AgreeYa Solutions',
  'annalect india',
  'Lowe’s',
  'BMC Software',
  'accolite software india pvt ltd',
  'Paytm Money',
  'Weave',
  'Barclaycard',
  'eCopy',
  'VMWare Denmark',
  'OpTel Informatik',
  'Kronos',
  'Chegg',
  'Sophos',
  'Micron Technology',
  'Hewlett Packard Enterprise',
  'airtel x labs',
  'Integral Ad Science',
  'ConnectWise',
  'Dell EMC',
  'tavisca, a cxloyalty technology platform (division of jp morgan chase & co.)',
  'analogic automation pvt ltd',
  'HSBC Bank Australia',
  'Ness',
  'NCR Corporation',
  'Zensar Technologies',
  'Principal Edge Active Income',
  'Think360',
  'BBD',
  'Opcito',
  'HCL Software',
  'ContiNube',
  'Interactive Data Managed Solutions',
  'Arrow Electronics',
  'TestingXperts',
  'CGI Sverige',
  'Ivy',
  'Sterlite Technologies',
  'spotmentor technologies private ltd',
  'Optiva',
  'Congruex',
  'BETSOL',
  'BlueConch Technologies',
  'HSBC India',
  'Saeloun',
  'Thomson Reuters',
  'adidas',
  'Digit Insurance',
  'Paytm',
  'Affirma Consultancy',
  'Faurecia',
  'BRIDGEi2i Analytics Solutions',
  'Tata Sky Ltd.',
  '617MediaGroup',
  'MobiPrimo Technologies',
  'Predix',
  'Hughes Systique',
  'Dish Network',
  'tsystems systems india private limited',
  'Intel Security',
  'CodeBlock',
  'airtel africa digital labs',
  'Qualys',
  'Indian Railways',
  'Tieto Support Services',
  'HERE',
  'Agiliad',
  'NICE inContact',
  'HERE Technologies Chicago',
  'iQuadra Information Services LLC.,',
  'TietoEVRY',
  'ThoughtworksThoughtworks',
  'Amadeus',
  'LastPass',
  'Nous Infosystems',
  'mfine',
  'Veritas Technologies',
  'Vitech Systems',
  'Empower Retirement',
  'Mobileum',
  'State Bank of India',
  'Cvent',
  'pccw solutions limited',
  'Tricentis',
  'Birlasoft',
  'Druva',
  'Clairvoyant',
  'Dell Technologies',
  'Pineapple Street Media',
  'Global Payments',
  'XFINITY on Campus',
  'citi development corp ltd',
  'SAP',
  'Adobe',
  'bwin',
  'Tetrasoft',
  'Google',
  'CIGNEX',
  'Spotfire',
  'Tetra Pak',
  'Avaya',
  'Vahan',
  'Lexmark',
  'Bergen Engines',
  'Programmers - Software Development Company',
  'UpGrad',
  'Patni Computer Systems',
  'Agilyst',
  'Boundary',
  'SpectraMedix',
  'Citrix Systems',
  'Sapiens International Corporation',
  'T-Systems International',
  'flightcase it services p ltd',
  'Altran',
  'The Information Company Private Limited',
  'Wissen Technology',
  'BlackRock',
  'british telecom india',
  'GYTWorkz',
  'Ericsson',
  'Expedia Group',
  'Zephyr Development Corp.',
  'Blume Global',
  'Rockwell Automation',
  'one.com',
  'Concentrix Corporation',
  'COFORGE',
  'Fidelity International',
  'dsk digital technologies pvt.ltd.',
  'Truein',
  'fantastic athletes corporation',
  'Lincoln Motor Company',
  'ril jio infocomm ltd',
  'NTT DATA',
  'Tavant',
  'capita software',
  'Aon Brazil',
  'Reliance Jio',
  'Finastra',
  'Agoda.com',
  'Walker Digital Table Systems',
  'Emtec',
  'Tecnotree',
  'mobily infotech india pvt ltd',
  'Sense Intellifield',
  'Oracle',
  'bnp paribas india solutions private limited',
  'Atos',
  'techwave consulting uk limited',
  'hsbc global technologies',
  'cognome',
  'DBS HotSpot',
  'Tomorrow'],
 ['Cisco'],
 ['Qualcomm',
  'Intel India',
  'Nvidia GPU Ventures',
  'Harman International Industries',
  'L&T Technology Services Ltd.',
  'Wipro Technologies',
  'AMD',
  'NXP Semiconductors',
  'Xilinx',
  'Apple',
  'Microsoft',
  'Xperia',
  'Arm Holdings',
  'Samsung Electronics',
  'Western Digital',
  'BigMachines',
  'Tech Mahindra',
  'IDENT Technology',
  'Samsung Pay',
  'FICO',
  'Blue Yonder',
  'Aeries Technology Group',
  'Mirafra Technologies',
  'ArchPro Design Automation',
  'Uber',
  'Amazon',
  'Capgemini',
  'PayPal',
  'Salesforce',
  'Radisys',
  'Gap Inc',
  'Micron Technology',
  'Broadcom Limited',
  'ServiceNow',
  'TI Ventures',
  'pk india',
  'MosChip Technologies Limited',
  'MaxLinear',
  'Infosys',
  'SunRay Construction Solutions LLC',
  'Graviton Research Capital',
  'Qvantel',
  'A Bullseye View',
  'smartron india pvt ltd.',
  'Progress Software Spain',
  'Franklin Templeton',
  'Belafonte TACOLCY',
  'park group of companies',
  'Zilogic Systems',
  'general electric (ge) india technology centre',
  'blinkit',
  'Experitest',
  'Blaize',
  'Qual IT',
  'Tata Consultancy Services',
  'Cerner',
  'NCR Corporation',
  'Mathworks',
  'GAMEFACE.AI',
  'ValueMomentum',
  'Intel Corporation',
  'Cadence Design Systems',
  'CA Technologies',
  'Arcesium',
  'dubai electricity & water authority - dewa',
  'Ivy',
  'SBM NAUVATA',
  'Juniper Networks',
  'Seagate Technology',
  'Freescale Semiconductor',
  'Veritas Technologies',
  'Sasken Communication Technologies',
  'Tessolve Semiconductor',
  'Royal Dutch Shell',
  'Si2Chip Technologies Pvt. Ltd.',
  'Nutanix',
  'ignitarium technology solutions pvt ltd',
  'STMicroelectronics',
  'collabera',
  'Marvell',
  'Google',
  'wipro vlsi',
  'Wells Fargo Financial',
  'InQuira',
  'ON Semiconductor',
  'Aricent',
  'Qubercomm',
  'Lantronix',
  'Coresonic',
  'Citibank India',
  'Chordiant Software',
  'Grab']]

In [167]:
######                               Employee count their ex-employees work
df1["companies_where_their_ex_employees_work"][88]['count']
Employee_count_their_ex_employees_work=[]
for i in range(60126):
    Employee_count_their_ex_employees_work.append(df1["companies_where_their_ex_employees_work"][i]['count'])

Employee_count_their_ex_employees_work[7:24]

[37, 103, 2, 48, 11, 1, 88, 2, 12684, 1, 7, 4, 2, 7, 72, 19595, 561]

In [168]:
list(df1.index)

['altran technologies india pvt ltd',
 'L&T Technology Services Ltd.',
 'Amdocs',
 'Xperia',
 'Ultra-Scan Corporation',
 'Adani Gas',
 'Benecke-Kaliko',
 'Graphene Semiconductors',
 'Mercedes-Benz Research and Development India',
 'Ceat Tyres Limited',
 'Global Edge Software',
 'Zenith Software',
 'Delta Power Electronics',
 'Siemens',
 'mts technologies ltd',
 'Tech Mahindra',
 'pronto consulting services pvt ltd',
 'DesignTech Systems',
 'Airspan Networks',
 'Bull Academy and IT Services',
 'Odysseus Solutions',
 'Nvidia GPU Ventures',
 'Wipro Technologies',
 'NTT DATA',
 'MaxByte Technologies',
 'skb builders india ltd',
 'indus projects ltd panipat',
 'IDS Next',
 'therefore consultancy and services pvt ltd',
 'SLK Software Services Pvt Ltd',
 'loginware softtech',
 'Chubb Financial Solutions',
 'nerdyturtlez.com',
 'GE Healthcare',
 'cgc converse technologies pvt ltd.',
 'prime edge info solutions private limited',
 'Tata Consultancy Services',
 'Xylem Water Solutions',
 'Synamedia',
 'Engineers India',
 'Aarvi Encon',
 'dharmsinh desai university',
 'motherson automotive technologies & engineering',
 'Hitachi Energy',
 'Story Digital',
 'Saankhya Labs',
 'Tessolve Semiconductor',
 'comtrol industries pvt. ltd.',
 'Inforaise',
 'Signify',
 'model engineering college',
 'GKN Aerospace',
 'Klaus IT Solutions',
 'karnex software solutions pvt. ltd.',
 'Rishabh Software',
 'emids',
 'buildstorm technologies',
 'exploreembedded',
 'abak electrofab engineering pvt.ltd',
 'Altran',
 'PerfectVIPs',
 'BlackPepper Technologies',
 'Tata Motors',
 'Volvo Cars',
 'InSync Healthcare Solutions',
 '617MediaGroup',
 'Concur Global Engineering Solutions',
 'hsl ground engineering',
 'TITAN GS',
 'ferchau engineering',
 'Cyient',
 'Kudelski Group',
 'SWECO',
 'chinese railway signalling & communication design',
 'amara raja group',
 'defence avionics research establishment',
 'ziox mobiles',
 'Emersion',
 'marine electricals (india) private limited',
 'Star Knowledge',
 'mel systems and services ltd.',
 'Enphase Energy',
 'aureate india',
 'fdes design automations',
 'Bosch',
 'HD Fire Protect',
 'kgc engineering project pvt.ltd.',
 'Avench systems',
 'data patterns (india) pvt ltd',
 'Mavenir',
 'collabera',
 'toyota kirloskar motor private ltd (tkm), bidadi',
 'Stratogent',
 'piping world',
 'Tata Technologies',
 'global edge software limited',
 'Telescope Services AB',
 'Willow',
 'CNH Industrial',
 'Pearson',
 'Sterlite Technologies',
 'marine electricals (india) limited',
 'Capgemini',
 'GMM Pfaudler',
 'the anup engineering limited - india',
 'Nex-G Exuberant Solutions',
 'Augen Technologies Software',
 'tata sikorsky aerospace limited',
 'Johnson Controls',
 'Siemens Gamesa Renewable Energy',
 'Quantiphi',
 'SUN Mobility',
 'techflux',
 'Intel India',
 'Invictus',
 'Airbus (Commercial Aircraft)',
 'Caresoft Global',
 'MindTree',
 'Mahindra Rise',
 'Celegence',
 'Doubtnut',
 'lonsenkiri chemicals limited',
 'Boston Technology Corporation (BTC)',
 'Hettich',
 'Zeppelin Systems',
 'Weatherford International',
 'Intuit',
 'zf electronics tvs india private limited',
 'Urjanet',
 'Visiontek',
 'sapizon technologies llp',
 'Barquecon Technologies',
 'LG Soft India',
 'Eximius Design',
 'LNTECC (LnT Engineering and Construction)',
 'Axis',
 'hanuman automation pvt. ltd.',
 'finitiatives learning india pvt. ltd',
 'wallmart',
 'Fresher',
 'GAVS Technologies',
 'NeoSOFT Technologies',
 'Robert Bosch Engineering & Business Solutions',
 'associate engineer at larsen & toubro technology services',
 'Dinamic-Laser',
 'Ranosys',
 'suresoft systems pvt ltd - india',
 'Linde Engineering',
 'Aker Solutions',
 'strix wireless systems pvt ltd',
 'flem consultants pvt ltd',
 'blue rose technologies',
 'technovations software pvt ltd',
 'Bechtel Corporation',
 'SABIC',
 'Pareteum',
 'thyssenkrup industrial solutions',
 'Cognizant',
 'vCentric Technologies',
 'Boeing Australia',
 'TATA Elxsi',
 'Nissan Motor Corporation',
 'aanjaneya aerodynamics pvt ltd',
 'Bosch Vietnam Co',
 'proteck machinery pvt. ltd',
 'publicity & sponsorship - radio hub',
 'Collins Aerospace',
 'SPB-PC',
 'ElectroLab',
 'Globant',
 'ArYuPay Technologies',
 'General Motors',
 'emerson process chennai pvt ltd.',
 'DynaMac Holdings',
 'Red Hat',
 'Brose North America Inc',
 'Avineon India',
 'BR Softech Pvt Ltd',
 'musrf - mechanical department',
 'cetex petrochemical industry, chennai',
 'Heurtey Petrochem',
 'maharaja sayajirao university of baroda, vadodara',
 'Stratosphere IT Services',
 'Metso Outotec',
 'takviksh engineering pvt limited',
 'nxfee innovation',
 'AMD',
 'HCL Technologies',
 'Ericsson Ventures',
 'torrent cables limited has become torrent power limited',
 'Orange Business Services',
 'virtuell hire',
 'spi - software paradigms international',
 'neo structo',
 'Skipper',
 'Cientra',
 'Sasken Communication Technologies',
 'tuv rheinland india',
 'base control tech',
 'Aurus',
 'Ola Electric',
 'Pallaton Technologies',
 'UltraTech Cement Ltd',
 'Vali Management Services',
 'larsen and toubro technology services',
 'Draw Tap GIS',
 'skanray healthcare pvt. ltd',
 'satven',
 'for self',
 'Chetu',
 'Trane Technologies',
 'Parallel Wireless',
 'Dell',
 'synapse design inc.',
 'Honeywell Combisafe',
 'XFINITY on Campus',
 'HCL Software',
 'Tricon Infotech',
 'Unilog',
 'SCOPE T&M',
 'Xilinx',
 'auma india pvt ltd',
 'Mobiquity',
 'Uber Project Lighting Pvt Ltd',
 'jacob engineering india privatelimited',
 'lafargeholcim global digital hub',
 'balwan agro industries pvt. ltd.',
 'Officesupplies.com',
 'NXP Semiconductors',
 'Hewlett Packard Enterprise',
 'ThyssenKrupp System Engineering',
 'o.l.c.i. engineering india pvt. ltd.',
 'linear rotary equipment',
 'Alstom',
 'eurofins it solutions india pvt. ltd',
 'Cognizant Softvision',
 'Suzlon Energy Ltd',
 'wärtsilä finnland oy',
 'Wipro',
 'springspree',
 'L&T Infotech',
 'ambigai consultancy services india',
 'Mott MacDonald',
 'VE Commercial Vehicles',
 'Infosys',
 'KSK Power Venture',
 'alten india',
 'TE Connectivity',
 'Xoriant',
 'Mobile Programming LLC.',
 'optimuslogic systems pvt ltd',
 'sprint consys pvt. ltd.',
 'Y MEDIA LABS',
 'eMudhra',
 'placementseason.com',
 'Allegion',
 'KPIT Technologies',
 'HSBC Bank Australia',
 'Sumeru Software Solutions',
 'PathPartner Technology',
 'BigMachines',
 'Caterpillar',
 'Confidential',
 'Mastek',
 'samsung electro-mechanics',
 'Quest Digital Pte. Ltd.',
 'Cadence Design Systems',
 'DSP Group',
 'John Deere Brazil',
 'Make A Difference',
 'GE Reports',
 'IBaseIT',
 'Siemens Technology India',
 'dhruvisha hvac systems pvt. ltd',
 'Alethea Communications',
 'Loyal Equipments',
 'AMETEK',
 'Crestron Electronics',
 'Aricent',
 'Lucy Electric',
 'ABB eMart',
 'Innovellent Technologies',
 'ArchPro Design Automation',
 'Western Digital',
 'virtual forest',
 'larson & toubro lnfotech limited.',
 'Menlo Worldwide Logistics',
 'allscripts healthcare, llc',
 'brose india automotive systems private limited',
 'SonicWALL',
 'Joyson Safety Systems',
 'Honda R&D Americas',
 'Pace Automation Limited',
 'sigtech wireless technologies',
 'Xchanging',
 'Adroit Business Solutions, Inc.',
 'TechnipFMC',
 'Lennox International',
 'Si2Chip Technologies Pvt. Ltd.',
 'Mettler Toledo',
 'gulfbank-kuwait',
 'Digital Processing Systems',
 'sigma computing solutions',
 'mirafra software technologies private limited - client intel technologies india pvt ltd',
 'glatt systems private limited',
 'fabtech technologies international limited',
 'Lear Corporation',
 'Mphasis',
 'Petrofac',
 'TresVista Financial Services',
 'american megatrends india pvt ltd',
 'In Time Tec',
 'voltamp transformers ltd',
 'tool comp systems',
 'encube labs',
 'pegasus racing',
 'arknewtech',
 'Qualcomm',
 'Reliance Industries',
 'Marquis Hot Tubs',
 'Accenture',
 'suzlon wind energy corporation (sweco)',
 'Utthunga Technologies',
 'Varroc Lighting Systems',
 'Valeo',
 'aeronatical development agency',
 'resnova technologies pvt. ltd',
 'Legato Health Technologies',
 'DXC Technology',
 'Cisco',
 'clasteck engineering pvt ltd',
 'mybox technologies pvt. ltd. ( a hero electronix venture)',
 'srm technology private lmt',
 'Wafer Space',
 'Sapiens International Corporation',
 'BitClass',
 'Tally Solutions',
 'Schneider Electric Sverige',
 'riverside utilities pvt. ltd.',
 'Toastmasters International',
 'zenith engineering corporation - india',
 'neyveli lignite corporation india limited',
 'ZF Friedrichshafen',
 'Berg Propulsion International',
 'Phi Education Solutions',
 'Creative Synergies Group',
 'V2Soft Inc',
 'FlamencoTech',
 'STMicroelectronics',
 'm j woods pirangut',
 'swan electric engineering company private limited',
 'Span Systems',
 'MAAYEE',
 'assured service',
 'Scientific Publishing Services',
 'path partner technology',
 'ANRITSU CORPORATION',
 'AGS Health',
 'jk electricals',
 'pacecom technologies pvt ltd',
 'snv tools india ltd',
 'MRF',
 'flowserve india controls pvt ltd',
 'Huawei Technologies',
 'Capillary Technologies',
 'Qualys',
 'MaxLinear',
 'Fiserv',
 'QuEST Global Services',
 'Apexon',
 'president motors - india',
 'prabhat electronics & electrical',
 'prijai heat exchangers pvt ltd',
 'Coresonic',
 'L&T-Sargent & Lundy',
 'Ahex Technologies',
 'Zebra Ventures',
 'Wimera',
 'DIGICOMM',
 'aas pass',
 'coffeecode',
 'Southern Electronics',
 'Flex',
 'Tangent Techno Labs',
 'Atlas Copco',
 'i2i telesolutions & telemedicine pvt.ltd',
 'Rockwell Automation',
 'Harman International Industries',
 'omega engineers',
 'OpenFive',
 'IDENT Technology',
 'pyrotech electronics unit 2 udaipur',
 'Salesforce',
 'IndaPoint Technologies Pvt LTd',
 'Air Products and Chemicals',
 'Cerence',
 'click2net services pvt ltd',
 'navonmesh prasar foundation | नवोन्मेष प्रसार फाउंडेशन',
 'itellisecure pvt ltd',
 'Bosch Chassis Systems India',
 'l&t audco',
 'Communication Security Group',
 'Consolidated Service Group',
 'idaq automation',
 'autoone engineering services pvt ltd',
 'xchangetech star alliance llp',
 'xytel india pvt ltd',
 'ZF Openmatics',
 'Nous Infosystems',
 'National Aerospace Laboratories',
 'Silicon Labs',
 'Building Blocks Learning Solutions',
 'Kiewit Corporation',
 'Leica Biosystems',
 'Mechlin Technologies',
 'microwatt energy systems pvt ltd',
 'mobiquity inc - india',
 'CreditVidya',
 'Bharat Heavy Electricals',
 'global edge software ltd.',
 'GE Renewable Energy',
 'ITTStar Consulting, LLC',
 'valdel engineers & constructors (s&b engineers & constructors, india)',
 'John Deere',
 'Elektrobit Oyj',
 'Worley',
 'ggs technology pvt.ltd',
 'l&t mhps ltd',
 'MRI Software',
 'Horizontal Digital',
 'ExxonMobil',
 'Addverb',
 'MSC Software',
 'Data Tech Computers',
 'Aptiv',
 'waferspace semiconductor',
 'anewa engineering pvt. ltd.',
 'bsptcl',
 'fritzmeier motherson cabin engineering limited',
 'snc lavalin engineering india private limited - mumbai',
 'sarvakarma solutions pvt ltd',
 'iec air tools pvt ltd',
 'Vestas',
 'Alchemy Techsol',
 'Lutron Electronics',
 'solize india technologies private limited (formerly csm software pvt. ltd.)',
 'Hyundai Mobis',
 'mrr embedded systems pvt ltd',
 'pima controls pvt. ltd.',
 'sahajanand infra',
 'PBOPlus Consulting Services Pvt Ltd',
 'Phillips',
 'denfab consulting engineers pvt ltd',
 'Tide',
 'S&P Global Market Intelligence',
 'WarnerMedia',
 'Vector India',
 'Sulzer',
 'Qualitrol',
 'toshiba embeeded software india pvt ltd.',
 'Bluewater Energy Services',
 'Reliance Jio',
 'indian institute of information technology design & manufacturing kancheepuram',
 'BD',
 'TVS Logistics Services',
 'ABM Respiratory Care',
 'majesco software and solution india private limited',
 'reliance composites solutions',
 'IBM',
 'Visvesvaraya National Institute of Technology',
 'Fluor',
 'pdt cleantech solutions pvt ltd',
 'delta associate engineering consultant',
 'Magna International',
 'Robosoft Technologies',
 'Berry Plastics',
 'Onward Technologies',
 'Inzi Controls',
 'iot anwesha engineering & construction limited',
 'WMS',
 'r.subramanian consultant engineers',
 'corest gestion comercial sl',
 'nessa illumination technologies pvt ltd',
 'powerline',
 'Avancer Software Solutions Pvt. Ltd.',
 'hcl talentcare',
 'MAQ Software',
 'Cypress Creek',
 'Vodafone Idea',
 'Autoliv',
 'vadron designs',
 'vivartan technologies',
 'BAeHAL Software',
 'huawei india',
 'Girmiti Software',
 'welmade locking systems pvt ltd',
 'Kirloskar Oil Engines',
 'carrier fire & security',
 'Mistral Solutions',
 'Healthvista India',
 'Alfa-Laval',
 'searching job',
 'Husqvarna',
 'moog india technology center private limited',
 'VVDN Technologies',
 'enter engineering group',
 'imonitor solutions india pvt ltd',
 'digital14',
 'Nasdaq',
 'Nexteer Automotive',
 'JEF Techno Solutions',
 'Eaton',
 'Medtronic Brain Therapies - Neurosurgery',
 'siyacon technologies pvt ltd,',
 'Samsung Pay',
 'Huntsman',
 'DAX',
 'Jacobs',
 'PM Group',
 'harman connected services',
 'megatech control pvt ltd',
 'adrit techno solutions',
 'Ani Integrated Services',
 'Walmart Global Tech India',
 'Lowe’s',
 'Expleo Solutions',
 'a r enterprize',
 'transworld technologies ltd.',
 'pogeyan technologies private limited',
 'Ingersoll Rand',
 'Bombardier Transportation',
 'Danske IT',
 'FIS',
 '5G Lab',
 'air products india',
 'jacobs engg india limited',
 'manshu comtel private limited, mumbai',
 '6D',
 'whirlpool global technology and engineering centre',
 'Jyoti Plastic Works',
 'Toyota Kirloskar Motor Pvt Ltd',
 'digisol network systems ltd',
 'MARELLI',
 's v national institute of technology, surat',
 'Deep Industries Limited',
 'COFORGE',
 'daulatram engineering services p. ltd.',
 'AC Talent Agency',
 'Andhra Pradesh Power Generation Corporation',
 'Pacific Northwest Title Holding Company',
 'Quest Informatics',
 'iQuanti, Inc.',
 'Lionbridge',
 'Indegene',
 'intellipredikt technologies pvt ltd',
 'McDermott International',
 'applied materials india',
 '99RetailStreet',
 'SRM Technologies',
 'Assurance Scientific Labs',
 'BorgWarner',
 'PlanetSpark',
 'DURA Automotive Systems',
 'Unisys',
 'sanguine infra tech',
 'visteon india',
 'Zilogic Systems',
 'Smiths Detection',
 'Cerner',
 'ZTE',
 'chemtrols emet',
 'mindgate',
 'precise 3d metrology & design solutions pvt ltd',
 'Nanostar',
 'technowave id systems private limited',
 'UL Eduneering',
 'Faurecia',
 'relysys technologies india private limited',
 'Neilsoft',
 'scienaptic ai',
 'Embitel Technologies',
 'elegant embedded solutions pvt ltd',
 'Amazon',
 'mosima engineering research consultancy & training',
 'larsen and tourbo technology and services',
 'UTC Aerospace Systems',
 'Ongil',
 'deepsensedigital',
 'dmietr- datta meghe institute of engineering technology and research',
 'jp infotech',
 'Vodafone Italy',
 'C2C Engineering',
 'SpanIdea',
 'volvo buses',
 'kgk group of companies, coimbatore',
 'SrinSoft Technologies',
 'marquardt india pvt. ltd',
 'synopsys (india) eda software private limited',
 'geolog',
 'phoenix racing srec',
 'Milwaukee Tool',
 'Ventana Medical Systems',
 'CSS Corp',
 'EY Startup Challenge',
 'ITT Corporation',
 'datashrubs',
 'Cairn India Ltd',
 'loneranger productions pvt.ltd',
 'IDC Technologies, Inc.',
 'ferrotic dies & moulds',
 'Tarang Software Technologies',
 'Bergen Engines',
 'Rohde & Schwarz',
 'Alpha Design Technologies',
 'MosChip Technologies Limited',
 'robert bosch india limited,bangalore',
 'Manipal Technologies Limited',
 'Renault-Nissan-Mitsubishi',
 'Sigma Electric Manufacturing Corp',
 'Jasmin Infotech',
 'Wind River',
 'bechtel oil, gas, & chemicals',
 'kaizen switchgear products',
 'Ignitarium',
 'sabre india',
 'intershala student partner',
 'Henkel Adhesive Technologies',
 'PRAVANA',
 'frelit energy pvt. ltd.',
 'Kreditbee Contact Us Now',
 'Genpact',
 'thinsil technologies',
 'cades-studec technologies india',
 'Frames Group',
 'cds infra projects limited',
 'shivam electricals pvt. ltd.',
 'anmerkung solutions private limited',
 'province infotech',
 'A-1 Technology',
 'ScaleneWorks People Solutions LLP',
 'Dow',
 'RedCarpetUp',
 'ciena india pvt ltd',
 'k.d.instrument services',
 'centum adeneo',
 'numero uno technik pvt ltd',
 'vijayjyot seats pvt. ltd.',
 'Panasonic',
 'Nabler',
 'quarbz info systems',
 'Niyama Global',
 'Technia',
 'toolcon systems',
 'sharma orthopedic india pvt. ltd.',
 'Umlaut',
 'sociograph solutions',
 'i - design engineering solutions limited',
 'Merittech',
 'Nokia',
 'madina group wll',
 'Apisero',
 'csd engineering services banagalore',
 'larson and toubro technology services',
 'IDBI Intech Ltd.',
 'SS&C Technologies',
 'DBS HotSpot',
 'Synerzip',
 'Cmetric',
 'Deloitte',
 'right ventures',
 'Plansee',
 'mw high tech projects india private limited',
 'Cloud Collab Technologies Pvt Ltd',
 'TOSHIBA',
 'SFO',
 'jnk india pvt. ltd',
 'ShawMan Software Pvt. Ltd.',
 'TransDigm',
 'Photon',
 'mach engineers',
 'mp consulting, llc',
 'Proliant Infotech',
 'information technology and services',
 'l&t kobelco manufacturing limited',
 'qtech ndt inspection service',
 'Whirlpool',
 'Sicame Group',
 'abu dhabi ports',
 'Wood',
 'ghafari-purohit architects and engineers private limited',
 'patni computer systems limited. andheri (e) mumbai',
 'OTSI',
 'UTC Climate, Controls & Security',
 'desha engineers (india) pvt ltd',
 'AVTEC LTD',
 'office of career services, iit hyderabad',
 'sculptasse',
 'Global Process Systems',
 'Ambigai Consultancy Services',
 'Belcan Corp.',
 'Cellcomm Solutions',
 'sinmado engineering (india) private limited',
 'Confirmation',
 'simpliv',
 'Vitesco Technologies',
 'Toshal Infotech',
 'Fabcon',
 'softlife technologies pvt ltd',
 'affluence infosystems',
 'infotech management consultancy',
 'CR Asia Group',
 'Beckman Coulter',
 'Cerium Systems',
 'techoz information and solutions pvt. ltd.',
 'bhavya enterprise',
 'Integra Microsystem pvt ltd',
 'Simplilearn',
 'Technosphere Labs',
 'think perfect',
 'malar electronics',
 'anewa',
 'surat mettalics ltd.',
 'Raja Software Labs',
 'wowexp technologies',
 'Gilbarco Veeder Root',
 'park controls & communications (p) ltd.',
 'csir-national geophysical research institute',
 'Delphi Technologies',
 'Magna Infotech',
 'NSA',
 'escorts agri machinery',
 'Wabtec',
 'jmd railtech pvt.ltd',
 'b.n.college of engg & technology at lucknow (up)',
 'Altimetrik Corp.',
 'kpit technologies limited (daf trucks)',
 'RGBSI',
 'brigosha technologies pvt. ltd',
 'EBSC',
 'VIP Industries',
 'Tektronix',
 'oerlikon textile india pvt ltd',
 'sheel oil and fats pvt ltd',
 'Ciena',
 'Magic Edtech',
 'maruti design & engineering services pvt ltd',
 'Vigo Care',
 'DevPort AB',
 'TiVo',
 'suzlon gujarat wind park limited',
 'Chegg India',
 'Accord Software & Systems',
 'Zuti',
 'Sciemetric Instruments',
 'Dell Technologies',
 'SRM University',
 'asmaja solutions',
 'kobelco construction equipment india',
 'Secure',
 'Backer Marathon',
 'Xlayer Technologies',
 'Cambium Networks',
 'msm consulting services(working for l&t technologies services)',
 'karnataka power transmission corp ltd (kptcl)',
 'CogniABle',
 'Zensar Technologies',
 'Apna',
 'Contract.fit',
 'anugraha valve castings private limited',
 'emerald jewels industries india ltd.',
 'Incedo Inc.',
 'robert bosch engineering and buisness solutions',
 'synergy circuits pvt ltd',
 'Samsung Electronics',
 'NEC Software Solutions',
 'Siemens Technology and Services',
 'Hughes Systique',
 'urvish enterprise',
 'Vashi Electricals Private Limited',
 'aquasub engineering(aqua group)',
 'HM Group',
 'Hidden Brains InfoTech',
 'lucas tvs ltd',
 'AUMA',
 'rhine engineering pvt. ltd.',
 'Jamjoom Medical Industries',
 'moschip semiconductor alumni',
 'Kantar',
 'TQuanta',
 'sumeru software solutions limited',
 'ATMECS',
 'Signus Labs',
 'java developer',
 'Rishabh Engineering Services',
 'linde engineering india',
 'Gibsons Games',
 'velankani electronics private limited',
 'fouress group',
 'jacob engineering',
 'KONE France',
 'felis leo ventures',
 'Fidelity',
 'Volvo Trucks',

# 1. Read the data from “assign_chubb_engineering .json” and convert it into a table with columns:

In [169]:
new_table={'Company uuid ':df1['company_uuid'],\
          'Company Name':list(df1.index),\
          'Employees Count':employees_count,\
           'List of companies they hired from':companies_they_hire_from_new,\
          'Employee count they hired':count,\
          'List of companies their ex-employees work':companies_their_ex_employees_work,\
          'Employee count their ex-employees work':Employee_count_their_ex_employees_work,\
          'IIT Count':iit_count,\
          'IIT Fresher Count':iit_fresher_count,\
          'NIT Count':nit_count,\
          'NIT Fresher Count':nit_fresher_count,\
          'Is score calculated':df1['is_score_calculated'],\
          'Tier-1 College Density Score':df1['Department_Tier-1_College_Density_Score'],\
          'Tier1 College Freshers Density Score':df1['Department_Tier-1_College_Freshers_Density_Score']}

### So as we can see that the columns have been added to the table

In [170]:
Table=pd.DataFrame(new_table)
#Table=Table.reset_index()
#df = df.drop('column_name', axis=1)
#Table=Table.drop('index',axis=1)
Table.head()

,Company uuid,Company Name,Employees Count,List of companies they hired from,Employee count they hired,List of companies their ex-employees work,Employee count their ex-employees work,IIT Count,IIT Fresher Count,NIT Count,NIT Fresher Count,Is score calculated,Tier-1 College Density Score,Tier1 College Freshers Density Score
altran technologies india pvt ltd,None,altran technologies india pvt ltd,1,[L&T Technology Services Ltd.],1,NaN,0,0,0,0,0,False,0.00001,0.00001
L&T Technology Services Ltd.,,L&T Technology Services Ltd.,6890,"[HCL Technologies, Tech Mahindra, Wipro Techno...",4019,[Robert Bosch Engineering & Business Solutions...,2192,16,7,13,3,True,0.004499,0.00464
Amdocs,fbd567c5e7395b46974ece634a19ff2e,Amdocs,1711,"[Tata Consultancy Services, Infosys, Cognizant...",1614,"[Tata Consultancy Services, Accenture, Tech Ma...",733,4,0,5,1,False,0.00526,0.035714
Xperia,7aa9a32dd8f27a05646e7317af05959b,Xperia,6,"[Ultra-Scan Corporation, Telescope Services AB...",6,[Cisco],1,0,0,0,0,False,0.00001,0.00001
Ultra-Scan Corporation,,Ultra-Scan Corporation,1140,"[Wipro Technologies, Tata Consultancy Services...",1102,"[Qualcomm, Intel India, Nvidia GPU Ventures, H...",246,63,0,17,0,False,0.07193,0.00001

In [171]:
Table.tail()

,Company uuid,Company Name,Employees Count,List of companies they hired from,Employee count they hired,List of companies their ex-employees work,Employee count their ex-employees work,IIT Count,IIT Fresher Count,NIT Count,NIT Fresher Count,Is score calculated,Tier-1 College Density Score,Tier1 College Freshers Density Score
babu it jobs,None,babu it jobs,1,[Tech Mahindra],1,NaN,0,0,0,0,0,False,0.00001,0.00001
capital honda service centre,,capital honda service centre,0,NaN,0,[Tech Mahindra],1,0,0,0,0,False,0.00001,0.00001
systems plus llc,,systems plus llc,0,NaN,0,[Tech Mahindra],1,0,0,0,0,False,0.00001,0.00001
gemini traze rfid pvt ltd,,gemini traze rfid pvt ltd,0,NaN,0,[Tech Mahindra],1,0,0,0,0,False,0.00001,0.00001
radiate e-services pvt. ltd.,,radiate e-services pvt. ltd.,0,NaN,0,[Tech Mahindra],1,0,0,0,0,False,0.00001,0.00001

In [172]:
Tier1CollegeFreshersStrength=[]
Tier1CollegeStrength=[]
for i in range(60126):
    val=(Table['IIT Fresher Count'][i]+Table['NIT Fresher Count'][i]) * Table['Tier1 College Freshers Density Score'][i]
    Tier1CollegeFreshersStrength.append(int(val))
    val2=(Table['IIT Fresher Count'][i]+Table['NIT Fresher Count'][i]+Table['IIT Count'][i]+Table['NIT Count'][i]) * Table['Tier-1 College Density Score'][i]
    Tier1CollegeStrength.append(int(val2))
Tier1CollegeStrength[3:21]
Table['Tier-1 College Freshers Strength']=Tier1CollegeFreshersStrength
Table['Tier-1 College Strength']=Tier1CollegeStrength

# 2. Find number of Null values in each column

In [173]:
print(Table.isnull().sum())

Company uuid                                 12449
Company Name                                     0
Employees Count                                  0
List of companies they hired from            34628
Employee count they hired                        0
List of companies their ex-employees work    16108
Employee count their ex-employees work           0
IIT Count                                        0
IIT Fresher Count                                0
NIT Count                                        0
NIT Fresher Count                                0
Is score calculated                              0
Tier-1 College Density Score                     0
Tier1 College Freshers Density Score             0
Tier-1 College Freshers Strength                 0
Tier-1 College Strength                          0
dtype: int64

# 3.Add a column ‘List of companies where hiring companies hire from’. It contains companies where the hiring companies of current company hires its employees. For example, company A hire from companies (B, C, D) then ‘List of companies where hiring companies hire from’ for company A has all the companies where B or C or D companies hire

In [174]:
#index_no = df.columns.get_loc(col_name)


#change the index of the table to company name and as we know the company to which hiring company hire
#we can again search through the company name which we got  in the dataframe.column
hiring_companies_hire=[]
for i in range(60126):
    if type(Table['List of companies they hired from'][i])==float:
        company=np.nan
        hiring_companies_hire.append(company)
    else:
        company = Table['List of companies they hired from'][i][0]
        hiring_companies_hire.append(Table['List of companies they hired from'][company])

In [175]:
hiring_companies_hire[2:4]

[['Cognizant',
  'Infosys',
  'Wipro Technologies',
  'Accenture',
  'Tech Mahindra',
  'HCL Technologies',
  'IBM',
  'Capgemini',
  'Trident Crating & Services',
  'Syntel',
  'CMC India Ltd',
  'MindTree',
  'L&T Infotech',
  'Mphasis',
  'iGATE Global Solutions',
  'Hexaware Technologies',
  'Virtusa',
  'Atos',
  'Future Focus Infotech',
  'HCL Infosystems',
  '617MediaGroup',
  'CSC',
  'General Motors',
  'Ericsson Ventures',
  'Cybage Software',
  'NTT DATA',
  'Hewlett Packard Enterprise',
  'CGI Sverige',
  'KPIT Technologies',
  'Birlasoft',
  'Publicis Sapient',
  'Cyient',
  'Genpact',
  'Concentrix Corporation',
  'Dell',
  'CSS Corp',
  'Amdocs',
  'Teamware',
  "BJYU's Future School",
  'Coforge',
  'Reliance Communications',
  'PRM Cloud Solutions',
  'Amazon',
  'foray software private limited',
  'Aon Brazil',
  'GlobalLogic',
  'Quest Digital Pte. Ltd.',
  'Chegg',
  'L&T Technology Services Ltd.',
  'Zensar Technologies',
  'Toastmasters International',
  'DXC Technology',
  '3i infotech',
  'Nelito Systems Ltd',
  'BigMachines',
  'Agilyst',
  'Sutherland',
  'UnitedHealth Group',
  'IBS Software Services',
  'Patni Computer Systems',
  'HSBC Bank Australia',
  'COFORGE',
  'Tata Communications',
  'Mastek',
  'Nokia',
  'Reliance Industries',
  'Sify Technologies Limited',
  'LBM Direct Marketing',
  'Aricent',
  'Synechron',
  'Total Compensation Solutions',
  'Refinitiv',
  'ITC Infotech',
  'BT',
  'IGT Solutions',
  'Persistent Systems',
  'Indus Net Technologies',
  'Harman International Industries',
  'Vodafone Italy',
  'National Informatics Centre',
  'YASH Technologies',
  'Belafonte TACOLCY',
  'Deloitte',
  'Reliance Jio',
  'WNS Global Services',
  'Sopra Steria',
  'ValueLabs',
  'IEEE Collabratec',
  'Microsoft',
  'Fresher',
  'IDC Technologies, Inc.',
  'Clover Infotech',
  'Thomson Reuters (Practical Law Company)',
  'general motors technical centre india private limited',
  'Chegg India',
  'HP',
  'Hinduja Global Solutions',
  'LNTECC (LnT Engineering and Construction)',
  'BNY Mellon',
  'Fujitsu Component Ltd.',
  'Polaris Software Lab',
  'Crown Solutions',
  'FIS',
  'Geeks for Geeks',
  'ValueMomentum',
  'CMS Info Systems',
  'Octagon Research Solutions Inc.',
  'Atos Syntel',
  'Majesco',
  'Robert Bosch Engineering & Business Solutions',
  'Infinite Computer Solutions',
  'Airtel',
  'Xigo',
  'Sellcraft Global Solutions',
  'cmc ltd',
  'HTC Global Services',
  'Honeywell Combisafe',
  'cmc limited',
  'ADP',
  'Internshala',
  'TatvaSoft',
  'Signus Labs',
  'collabera',
  'AIESEC',
  'Thirdware Solution',
  'Microland',
  'ShrubHub',
  'Teleperformance Group',
  'ICICI Home Finance',
  'Chetu',
  'Bank of America',
  'Infosys BPM Limited',
  'Genpact Headstrong Capital Markets',
  'Citibank India',
  'NeoSOFT Technologies',
  'The Centurion Bank of Punjab',
  'Datamatics',
  'Thomson Reuters',
  'TCE',
  'Infoview',
  'NIIT',
  'infosys ltd',
  'Dell Technologies',
  'Newgen Software Technologies',
  'Bharat Sanchar Nigam (BSNL)',
  'Viewpoint Datalabs',
  'CitiusTech',
  'Wells Fargo Financial',
  'Broadridge',
  'Tetrasoft',
  'IQVIA',
  '5G Lab',
  'Rolta',
  'coding club',
  'Barclays',
  'Hinduja Tech',
  'Mahindra Rise',
  'EASi',
  'Coding Ninjas',
  'innova solutions usa',
  'Centre for Development of Advanced Computing',
  'Cavisson Systems',
  'Dell Tech',
  'Fiserv',
  'Sapient Technologies',
  'Dell EMC',
  'Infostretch',
  'Prodapt Solutions',
  'Photon',
  'Allianz Technology',
  'PK Global',
  'Symantec Cybersecurity Services',
  'InQuira',
  'StrataCare',
  'Unisys',
  'Accel',
  'R Systems',
  'CDK Global',
  'Standard Chartered Botswana',
  'Make A Difference',
  'Web Spiders Inc.',
  'Xerox Europe',
  'Computer Society of India',
  'HERE Technologies Chicago',
  'Innova Solutions',
  'iNautix',
  'Deutsche Bank',
  'Team Computers',
  'QA InfoTech',
  'Siemens Technology India',
  'American Express',
  'Altran',
  'SAP Customers',
  'Cerner',
  'Happiest Minds Technologies',
  'Nous Infosystems',
  'Arbitron',
  'Exilant',
  'NTT DATA Global Services Corporation',
  'Teradata UK',
  'Morgan Stanley',
  'Acuvate',
  'CA Technologies',
  'EY Startup Challenge',
  'Digitate',
  'SRM University',
  'Silvertouch Technologies',
  'Google',
  'Hitachi Systems Micro Clinic',
  'Nvidia GPU Ventures',
  'Nielsen',
  'Bharat Heavy Electricals',
  'RapidValue Solutions',
  'Infogain Corporation',
  'Bharat Electronics',
  'Extramarks',
  'EXL Landa',
  'State Bank of India',
  'Temenos',
  'Incedo Inc.',
  'SLK Software',
  'Mindfire Solutions',
  'RM plc',
  'Siemens',
  'Tata Motors',
  'PwC India',
  'Prodboard',
  'Flex',
  'QualityKiosk Technologies Private Limited',
  'ABN AMRO Bank',
  'Sonata Software',
  'Cisco',
  'Sensiple Software Solutions Pvt Ltd',
  'amazon development centre (india) private limited',
  'Ramco',
  'Unisys (Schweiz) GmbH',
  'Ugam',
  'Nucleus Software',
  'Intellect Design Arena',
  'indian society for technical education',
  'Huawei Technologies',
  'ilabz technology',
  'Cygnet Infotech Pvt. Ltd.',
  'RMSI',
  'GeometricPLM',
  'Shanmugha Arts, Science, Technology & Research Academy',
  'GAVS Technologies',
  'MAQ Software',
  'Principal Financial Group',
  'The Royal Bank Of Scotland Private Limited Company',
  'Symphony Teleca Corporation',
  'Google Developers Group',
  'CommBank',
  'SailFin',
  'Diverse Lynx',
  'CompuCom',
  'Nucsoft',
  'Xoriant',
  'Sasken Communication Technologies',
  'NetConnect Global',
  'Optimize IT Systems',
  'Embee',
  'Altisource',
  'IEEE Computer Society',
  'smartData Enterprises',
  'Marlabs Inc',
  'National Aerospace Laboratories',
  'eInfochips',
  'Tata Technologies',
  'Axa Seguros',
  'A Bullseye View',
  'IndiaMART',
  'Servion',
  'IDBI Intech Ltd.',
  'LinuxWorld Informatics',
  'Financial Software & Systems',
  'Focus Academy For Career Enhancement',
  'JSW Steel',
  'Unified Infotech',
  'ELECTRONICS CORPORATION OF INDIA LIMITED',
  'Hurix Systems Private',
  'BLUE STAR INFOTECH',
  'Velocis Systems',
  'GE Healthcare',
  'BEO Software',
  'Force Motors',
  'Magna Infotech',
  'Indus Towers',
  'Fiat Chrysler Automobiles',
  'Trianz',
  'Samsung NewsRoom',
  'CNO Financial Group',
  'Verizon',
  'NICE Systems',
  'emids',
  'DAX',
  'Esri India',
  'SQS Software Quality Systems',
  'Sath',
  'TEKsystems',
  'Optum Frontier Therapies',
  'American Academy of Advertising',
  'NCR Corporation',
  'Cyber Infrastructure (p) Ltd',
  'the sparks foundation',
  'PCS Technology',
  'developer student clubs',
  'GTS (Global TeleSystems)',
  'TeamLease Services',
  'DRDO',
  'andhra pradesh state skill development corporation (apssdc)',
  'EC-Mobility',
  'ThinkPalm',
  'TechProcess Solutions',
  'Eastern Software Systems',
  'Steel Authority of India',
  'IndiaNIC Infotech Limited',
  'CoFoxDigital',
  'Indian Institute of Technology Kanpur',
  'Ashok Leyland',
  'Tata Docomo',
  'Maersk',
  'Supervalu',
  'infoview technologies pvt limited',
  'Fujitsu Icim',
  'YALAMANCHILI',
  'Datacore Technologies',
  'Techfest',
  'GSPANN Technologies',
  'ACM Digital Library',
  'sixsigma softsolutions pvt ltd',
  'Accelya Solutions',
  'Computer Science',
  'Paladion',
  'GLINDER',
  'Landmark Group',
  'Xavient Information Systems',
  'Lincoln Motor Company',
  'National Stock Exchange',
  'Tieto Support Services',
  'PrepBytes',
  'InApp Inc',
  'YouTube',
  'PwC',
  'Ness',
  'Telstra Media',
  'Rolls-Royce',
  'Black Knight',
  'Xceedance',
  'Skava',
  'teamlease digital',
  'McKinsey & Company',
  'EVRY India',
  'Allscripts',
  'Fidelity International',
  'R1 RCM',
  'H&R Block',
  'VVDN Technologies',
  'asap info systems pvt. ltd.',
  'Sears',
  'Jaguar Land Rover',
  'RS Software (India) Limited',
  'matrix media solutions (p) ltd',
  'Gateway Technolabs',
  'DST Systems',
  'Omnitech InfoSolutions Ltd.',
  'vCustomer',
  'Enterprise System Solutions Pvt. Ltd.',
  'tudip technologies',
  'InfoBeans Technologies Limited',
  'CMS Computers Limited',
  'NSEIT',
  'Indian Institute of Technology Bombay (IIT)',
  'Origin ITFS',
  'Aurionpro',
  'Bokanyi Consulting',
  'diligenta - a subsidiary of tata consultancy services',
  'WestPac',
  'Ebix',
  'Hindustan Aeronautics',
  'Armia Systems',
  'Safran Engineering Services',
  'Brillio',
  'Orion Innovation',
  'Dhirubhai Ambani Institute of Information and Communication Technology',
  'ACT (Atria Convergence Technologies Pvt. Ltd.)',
  'ArisGlobal',
  'Aviva Health',
  'doordarshan kendra',
  'Vedantu',
  'Ebix Consulting',
  'Etech Global Services',
  'naresh i technologies',
  'wipro technoligies',
  'FIGMD',
  'Fingent',
  'Aspire Systems',
  'Ecell',
  'IAP Company',
  'MRR Soft Inc.',
  'ABB eMart',
  'elitecore technologies pvt ltd.',
  'UST',
  'Inspirisys Solutions limited',
  'Celebal Technologies',
  'Sears Holdings India',
  'Quick Heal Technologies',
  'Trust Systems & Software',
  'Sterlite Technologies',
  'MicroObjects',
  'Infosenseglobal Inc',
  'Capital Numbers',
  'Indian Institute of Technology Madras',
  'PRGX',
  'BNP Paribas Fortis',
  'equiniti india',
  'ICON',
  'Datametica',
  'Lloyds Banking Group',
  'Adrenalin eSystems',
  'Jade Global',
  'Barclays Investment Bank',
  'RBS International',
  'arth - the school of technologies',
  'Altimetrik Corp.',
  'EdgeVerve',
  'UBS Delta',
  'Black Knight Financial Services',
  'NTT DATA Business Solutions',
  'Concord EFS',
  'BNP Paribas',
  'Professional Access',
  'Finastra',
  'Safran Corporate Ventures',
  'convergys india services private limited',
  'ANZ Investments',
  'L brands',
  'JR Technologies',
  'Icertis',
  'SRM Technologies',
  'ObjectFrontier',
  'Source One Management Services',
  'Annet Group',
  'eRevMax',
  'Adecco',
  'Adobe',
  'Innominds Software',
  'Polaris',
  'Business Intelligence Professionals',
  'Webgility',
  'Endocyte',
  'nelito systems limited ( a tata group company )',
  'Mercer (us) Inc.',
  'Orange Business Services',
  'PrimeSoft Solutions, Inc.',
  'JNET',
  'Fidelity',
  'ABM Knowledgeware',
  'Aditya Birla Fashion and Retail',
  'Oil and Natural Gas Corporation',
  'ATMECS',
  'Hudl',
  'Tesco',
  'Ocwen Financial Corporation',
  'Experion Technologies',
  'Q M CompuTech',
  'Daimler India',
  'techkriti, indian institute of technology kanpur',
  'Attinad Software',
  'Ameex Technologies',
  'Mobiloitte',
  'Saudi Telecom Company',
  'Logixal',
  'Bajaj Finserv',
  'Danske IT',
  'Allsec Technologies',
  'Prime Technology Group',
  'SIRO Clinpharm',
  'Sam Studio - Outsource business services provider',
  'Altair',
  'orion systems integrators, inc.',
  'Magnaquest Technologies Ltd',
  'InnoEye Technologies',
  'Ingram Micro Cloud',
  'Impetus Technologies',
  'Infosys Portland',
  'ISRO',
  'Virtual Galaxy Infotech Private Limited',
  'D+H',
  'evolve technologies and services (p) ltd.',
  'Theorem Advertising',
  'sapientnitro',
  'Hibu',
  'Harbinger Systems',
  'Hyundai Motor Company',
  'Confidential',
  'Allegis Group',
  'National Service Scheme 470 Mannar',
  'Gandhi Institute of Technology and Management',
  "innovation & entrepreneurship development centre (vignan e-cell), vignan's university",
  'Lionbridge',
  'iSOFT Group',
  'Idea Cellular',
  'Nagarro',
  'Nissan Motor Corporation',
  'Whirlpool',
  'Hughes Systique',
  'Hemmersbach',
  'Vodafone Idea',
  'NetCracker Technology',
  'Bosch Chassis Systems India',
  'FCS Software Solutions',
  'Pramerica',
  'Digital Minds Solutions',
  'JSoft Solutions Ltd.',
  'Amrita Vishwa Vidyapeetham',
  'Tata Steel BSL',
  'CtrlS',
  'Firstsource',
  'Novac Technology Solutions',
  'Regnant Software Solutions',
  'TCG Digital',
  'Vizag Steel',
  'AT&T',
  'Capita',
  'twenty19.com',
  'ASME',
  'Triassic Solutions',
  'Navigators Software',
  'Benecke-Kaliko',
  'WhiteHat Jr.',
  'Tata Teleservices',
  'FirstCry',
  'Schlumberger',
  'Suyati Technologies',
  'EpiComm Technologies',
  'NEC Software Solutions',
  'Keka HR',
  'Unacademy',
  'Petrolink',
  'Newton School',
  'tcsl',
  'Eagle Eye Home Inspections, Inc.',
  'BP Pratchaya Mahatkun',
  'Experis France',
  'Schneider Electric Sverige',
  'Carqueville Graphics',
  'Godrej & Boyce',
  'Magna International',
  'Hasura',
  'Stock Holding Corporation of India Limited',
  'Vodafone Global Enterprise',
  'Ramrao Adik Institute of Technology',
  'GE Power',
  'ZenQ',
  'asap infosystems pvt.ltd',
  'Maveric System',
  'Agility',
  'Zoho',
  'Eureka Forbes',
  'iOPEX technologies',
  'Simform',
  'SrinSoft Technologies',
  'VE Commercial Vehicles',
  'Muvi.com',
  'Unschool',
  'Pervacio',
  'Gaian Solutions',
  'ISTE',
  'Marks & Spencer',
  'Deluxe Media',
  'One97',
  'Invictus',
  'Lakshmi Machine Works',
  'MetLife',
  'JD Sports',
  'Tata IQ',
  'Infomerica',
  'Volante Technologies',
  'hsbc software development ind pvt ltd',
  'AgreeYa Solutions',
  'serveright consultants private limited',
  'yume by rhythmone',
  'Profinch Solutions',
  'DBS HotSpot',
  'Vyom Labs',
  'Enov8',
  'Woolworths',
  'du',
  'Satyam Computer Services Ltd.',
  'merzedez-benz',
  'Jean Martin',
  'AIG',
  'Nitor Infotech',
  'Scotiabank Chile',
  'Cerillion',
  'isource infosystems pvt ltd',
  'Bugcrowd',
  'Walmart Global Tech India',
  'Alcon Pharmaceuticals',
  'sunlife financial services pvt. ltd.',
  'iServeU',
  'Boeing Australia',
  'Contemi Solutions',
  'Globsyn',
  'infosys ltd.',
  'Landis+Gyr',
  'Finicity',
  'Metacube Software',
  'emerson export enginnering centre',
  'Bed Bath & Beyond',
  'Sagarsoft',
  'Brady Corporation',
  'scorg international consulting pvt. ltd.',
  'Expenzing',
  'Infocrats Web Solutions',
  'Attra',
  'GS Lab',
  'appright inc',
  'GEP',
  'NTT',
  'Chase Paymentech Europe',
  'Efkon India',
  'UPL',
  'Etihad Airways',
  'U-TO Solutions',
  'sharp software development india',
  'idc technologies solutions pvt ltd',
  'tetrasoft india pvt ltd',
  'TIAA',
  'Unilever',
  'national institute of technology delhi',
  'iQor',
  'HotelKey',
  'in-solutions global ltd',
  'autobyte private limited',
  'PTC',
  'oostelijke onderneming llp, subsidiary eastern enterprise',
  'Aditya Birla Group',
  'The DO School',
  'YourQuote',
  'Extranet Software Solutions',
  'Electronic Arts',
  'Reliance General Insurance',
  'Karmayog',
  'unikaihatsu software pvt. ltd.',
  'Efftronics',
  'Kaizen IT Services',
  'Moofwd',
  'samsung india electronics limited, noida',
  'HackerRank',
  'Indian Institute of Technology Kharagpur',
  'Cytel Corporation',
  'Coding Blocks',
  'Fullerton India',
  'SAE International',
  'Tulip Retail',
  'Prolifics',
  'nptel',
  'Nityo Infotech Services',
  'Bluecast Technologies',
  'Lear Corporation',
  'IMSI',
  'Rebaca Technologies',
  'indianic infotech ltd',
  'Trimax IT Infrastructure & Services',
  'Alstom',
  'Flipkart',
  'Entrepreneurship Cell, IIT Kharagpur',
  'olcademy',
  'Dhanush Infotech',
  'NGA HR (NorthgateArinso)',
  'Aptech Ltd.',
  'Harvard Business Review',
  'Standard Chartered Bank',
  'AVASOFT',
  'Tikona Infinet Limited',
  'Global IDs',
  'Vidyalankar Institute of Technology',
  'Digital Aptech',
  'Management Technology Consulting',
  'grapevine india',
  'Tavant',
  'PurpleTalk',
  'Sarla Technologies',
  'riviera, vit university',
  'Euronet Worldwide',
  'kuruksastra',
  'QBurst',
  'wti advanced technology ltd',
  'Textron',
  'm.kumarasamy college of engineering, karur',
  'LG Soft India',
  'LogictreeIT',
  'Airtel Africa',
  'Excellon Software',
  'Intel India',
  'Panamax Inc.',
  'Radixweb',
  'Xchanging',
  'ict infracon',
  'Airport Authority of India-AAI',
  'The Home Depot',
  'fast ml',
  'Vellore Institute of Technology',
  'EDIFIXIO INDIA PRIVATE LIMITED',
  'Redington',
  'Regionalverkehr Bern-Solothurn',
  'Hella',
  'Global Cloud Xchange',
  'Intern Theory Career Solutions',
  'foraysoftware pvt ltd',
  'Eaton',
  'Elisa',
  'National Innovation Center Nepal',
  'SLK Software Services Pvt Ltd',
  'SoluSoft',
  'onkar dies pvt. ltd.',
  'kpit technologies limited',
  'citixsys - ivend retail',
  'Unicommerce eSolutions Pvt. Ltd.',
  'Liberty Mutual Strategic Ventures',
  'Synsoft Global',
  'Nippon Data Systems',
  'Altruist Technologies',
  'Intense Technologies Limited',
  'OSI Consulting',
  'IKS Health',
  'BSES',
  'Scientific Publishing Services',
  'LearningMate',
  'Indian Air Force',
  'rle india',
  'Intelenet Global Services',
  'smart india hackathon',
  'Vsynergize',
  'Course Hero',
  'Intelliswift Software',
  'Minacs',
  'Next Sphere Technologies',
  'vignan university',
  'Motilal Oswal Financial Services',
  'none',
  'Lexmark',
  'Netmeds',
  'National Institute of Technology Rourkela',
  'FLSmidth',
  'Indian Institute of Technology Gandhinagar',
  'Helios & Matheson',
  'it analyst',
  'Cadence Design Systems',
  'digital avenues ltd.',
  'Apple',
  'Rivigo',
  'IVL - InfoVision Labs',
  'University of Hyderabad',
  'ADA Software',
  'Future Group',
  'finlogic technologies india private limited',
  'Omdena',
  'TELENOR FINANCIAL SERVICES AS',
  'BAeHAL Software',
  'Indusa',
  'Quinnox',
  'Futwork',
  'Megasoft',
  'Searce',
  'kolkata',
  'CyberTech International',
  'Oracle',
  'Webguru Infosystems Pvt.Ltd.',
  'Sofmen',
  'Sun Pharma',
  'Matrix Comsec',
  'sulekha.com',
  'Airtel Prepaid',
  'Syncronys Intl Inc',
  'Johnson & Johnson',
  'BidBlink',
  'Packt',
  'Kott Software',
  'iYogi',
  'AdMod',
  'Appsbee Technology Pvt. Ltd',
  'Inteliment',
  'Oppo',
  'I-Engineering, Inc.',
  'Mobius Knowledge Services',
  'Vertisystem',
  'Disys',
  'Walgreens',
  'Nationwide Building Society',
  'Mu Sigma',
  'Evelyn Learning Systems',
  'InterviewBit',
  'cygnet infotech llc',
  'Just Dial',
  'Appikr Labs',
  'Green Apex',
  'Swecha',
  'Mercedes-Benz Research and Development India',
  'Future Generali',
  'Calpine Group',
  'infalysis solutions',
  'geekonix',
  'Infibeam Avenues Limited',
  'tata cosultancy services limited.',
  'Tekplay',
  'JK Technosoft',
  'Sterlingsoft',
  'Codechef Business',
  'Kerala State Electricity Board',
  'British Airways',
  'PrepInsta',
  'cadsys (india) limited',
  'Chiltern International',
  'Avaya',
  'GirlScript Summer of Code',
  'Accion Labs',
  'Godrej Infotech',
  'Navayuga InfoTech',
  'Indian Railways',
  'Muskaan Dreams',
  'Samsung Pay',
  'atidan technologies pvt. ltd.',
  'SecurView',
  'shreyas tech solutions',
  'Syndrome Technologies',
  'Qantas',
  'Systime',
  'Kony',
  'Precision Techserve',
  'CIK Telecom',
  'PharmaNet',
  'seria applied research pvt ltd',
  'cytel statistical software & services private limited',
  'space applications centre, isro',
  'SunTec Business Solutions',
  'Benchmark ESG',
  'Essar Ports',
  'efftronics systems private limited',
  'SFO Technologies',
  'VDA Infosolutions',
  'InternIn',
  'ESDS Software Solution Limited',
  'Sony Pictures Entertainment',
  'ASAP Infosystems',
  'zairza',
  'STMicroelectronics',
  'CenturyLink',
  'Tops Technologies Pvt. Ltd.',
  'Gizmeon',
  'c-edge technologies limited',
  'Mobicule Technologies',
  'Bhabha Atomic Research Centre',
  'EbixCash Limited',
  'RGBSI',
  'ZS Associates',
  'Intelizign',
  'Infrasoft Technologies',
  'Signify',
  'Zenith Infotech',
  'Experis IT Pvt Ltd.',
  'ion-tata consultancy services',
  'OpenText',
  'national council of educational research and training ( ncert )',
  'ibm india private limited',
  'Elait',
  'Camp K12',
  'any.',
  'Tata Institute of Fundamental Research',
  'tcs maitree chennai toastmasters club',
  'reliance jio infocomm limited',
  'Mode Media',
  'studying',
  'Bosch',
  'SAP',
  'Tech Mahindra Business Services',
  'Torry Harris Integration Solutions',
  'Zylog Systems Limited',
  'Appnomic',
  'Arteria Technologies',
  'Base Information Management',
  'Medium',
  'Scope e Knowledge Center Pvt Ltd',
  'Micro Focus',
  'qualitest india',
  'Careers360',
  'Emerio',
  'Nexiilabs',
  'Allied Digital Services',

In [176]:
new_table={'Company uuid':df1['company_uuid'],\
          'Company Name':list(df1.index),\
          'Employees Count':employees_count,\
           'List of companies they hired from':companies_they_hire_from_new,\
          'Employee count they hired':count,\
          'List of companies their ex-employees work':companies_their_ex_employees_work,\
          'Employee count their ex-employees work':Employee_count_their_ex_employees_work,\
          'IIT Count':iit_count,\
          'IIT Fresher Count':iit_fresher_count,\
          'NIT Count':nit_count,\
          'NIT Fresher Count':nit_fresher_count,\
          'Is score calculated':df1['is_score_calculated'],\
          'Tier-1 College Density Score':df1['Department_Tier-1_College_Density_Score'],\
          'Tier1 College Freshers Density Score':df1['Department_Tier-1_College_Freshers_Density_Score'],\
          'List of companies where hiring companies hire from':hiring_companies_hire,\
          'Tier-1 College Freshers Strength':Tier1CollegeFreshersStrength,\
           'Tier-1 College Strength':Tier1CollegeStrength}

In [177]:
Table=pd.DataFrame(new_table)
Table.head()

,Company uuid,Company Name,Employees Count,List of companies they hired from,Employee count they hired,List of companies their ex-employees work,Employee count their ex-employees work,IIT Count,IIT Fresher Count,NIT Count,NIT Fresher Count,Is score calculated,Tier-1 College Density Score,Tier1 College Freshers Density Score,List of companies where hiring companies hire from,Tier-1 College Freshers Strength,Tier-1 College Strength
altran technologies india pvt ltd,None,altran technologies india pvt ltd,1,[L&T Technology Services Ltd.],1,NaN,0,0,0,0,0,False,0.00001,0.00001,"[HCL Technologies, Tech Mahindra, Wipro Techno...",0,0
L&T Technology Services Ltd.,,L&T Technology Services Ltd.,6890,"[HCL Technologies, Tech Mahindra, Wipro Techno...",4019,[Robert Bosch Engineering & Business Solutions...,2192,16,7,13,3,True,0.004499,0.00464,"[Wipro Technologies, Tata Consultancy Services...",0,0
Amdocs,fbd567c5e7395b46974ece634a19ff2e,Amdocs,1711,"[Tata Consultancy Services, Infosys, Cognizant...",1614,"[Tata Consultancy Services, Accenture, Tech Ma...",733,4,0,5,1,False,0.00526,0.035714,"[Cognizant, Infosys, Wipro Technologies, Accen...",0,0
Xperia,7aa9a32dd8f27a05646e7317af05959b,Xperia,6,"[Ultra-Scan Corporation, Telescope Services AB...",6,[Cisco],1,0,0,0,0,False,0.00001,0.00001,"[Wipro Technologies, Tata Consultancy Services...",0,0
Ultra-Scan Corporation,,Ultra-Scan Corporation,1140,"[Wipro Technologies, Tata Consultancy Services...",1102,"[Qualcomm, Intel India, Nvidia GPU Ventures, H...",246,63,0,17,0,False,0.07193,0.00001,"[Cognizant, Infosys, Tata Consultancy Services...",0,5

# 4. Based on Number of employees classify them into 9 categories and add a column with category number Number of employees: 

###### Category Number 1-10 :1 ; 11-50 : 2 ; 51-100 :3 ; 101-250 :4 ; 251-500 :5 ; 510-1000: 6 ; 1001-5000: 7; 5001-10000:8 ; 10000+: 9

In [178]:
Category_Number=[]
print(type(Table['Employees Count'][0]))
len(Table['Employees Count'])

<class 'numpy.int64'>

60126

In [179]:
Category_Number=[]
for i in range(60126):
    if Table['Employees Count'][i]>=1 and Table['Employees Count'][i]<=10:
        Category_Number.append(1)
    elif Table['Employees Count'][i]>=11 and Table['Employees Count'][i]<=50:
        Category_Number.append(2)
    elif Table['Employees Count'][i]>=51 and Table['Employees Count'][i]<=100:
        Category_Number.append(3)
    elif Table['Employees Count'][i]>=101 and Table['Employees Count'][i]<=250:
        Category_Number.append(4)
    elif Table['Employees Count'][i]>=251 and Table['Employees Count'][i]<=500:
        Category_Number.append(5)
    elif Table['Employees Count'][i]>=501 and Table['Employees Count'][i]<=1000:
        Category_Number.append(6)
    elif Table['Employees Count'][i]>=1001 and Table['Employees Count'][i]<=5000:
        Category_Number.append(7)
    elif Table['Employees Count'][i]>=5001 and Table['Employees Count'][i]<=10000:
        Category_Number.append(8)
    elif Table['Employees Count'][i]>=10001:
        Category_Number.append(9)
    else:
        Category_Number.append(0)

In [180]:
len(Category_Number)

60126

In [181]:
new_table={'Company uuid':df1['company_uuid'],\
          'Company Name':list(df1.index),\
          'Employees Count':employees_count,\
           'List of companies they hired from':companies_they_hire_from_new,\
          'Employee count they hired':count,\
          'List of companies their ex-employees work':companies_their_ex_employees_work,\
          'Employee count their ex-employees work':Employee_count_their_ex_employees_work,\
          'IIT Count':iit_count,\
          'IIT Fresher Count':iit_fresher_count,\
          'NIT Count':nit_count,\
          'NIT Fresher Count':nit_fresher_count,\
          'Is score calculated':df1['is_score_calculated'],\
          'Tier-1 College Density Score':df1['Department_Tier-1_College_Density_Score'],\
          'Tier1 College Freshers Density Score':df1['Department_Tier-1_College_Freshers_Density_Score'],\
          'List of companies where hiring companies hire from':hiring_companies_hire,\
          'Category_Number':Category_Number,\
          'Tier-1 College Freshers Strength':Tier1CollegeFreshersStrength,\
           'Tier-1 College Strength':Tier1CollegeStrength}

In [182]:
Table=pd.DataFrame(new_table)
Table.head()

,Company uuid,Company Name,Employees Count,List of companies they hired from,Employee count they hired,List of companies their ex-employees work,Employee count their ex-employees work,IIT Count,IIT Fresher Count,NIT Count,NIT Fresher Count,Is score calculated,Tier-1 College Density Score,Tier1 College Freshers Density Score,List of companies where hiring companies hire from,Category_Number,Tier-1 College Freshers Strength,Tier-1 College Strength
altran technologies india pvt ltd,None,altran technologies india pvt ltd,1,[L&T Technology Services Ltd.],1,NaN,0,0,0,0,0,False,0.00001,0.00001,"[HCL Technologies, Tech Mahindra, Wipro Techno...",1,0,0
L&T Technology Services Ltd.,,L&T Technology Services Ltd.,6890,"[HCL Technologies, Tech Mahindra, Wipro Techno...",4019,[Robert Bosch Engineering & Business Solutions...,2192,16,7,13,3,True,0.004499,0.00464,"[Wipro Technologies, Tata Consultancy Services...",8,0,0
Amdocs,fbd567c5e7395b46974ece634a19ff2e,Amdocs,1711,"[Tata Consultancy Services, Infosys, Cognizant...",1614,"[Tata Consultancy Services, Accenture, Tech Ma...",733,4,0,5,1,False,0.00526,0.035714,"[Cognizant, Infosys, Wipro Technologies, Accen...",7,0,0
Xperia,7aa9a32dd8f27a05646e7317af05959b,Xperia,6,"[Ultra-Scan Corporation, Telescope Services AB...",6,[Cisco],1,0,0,0,0,False,0.00001,0.00001,"[Wipro Technologies, Tata Consultancy Services...",1,0,0
Ultra-Scan Corporation,,Ultra-Scan Corporation,1140,"[Wipro Technologies, Tata Consultancy Services...",1102,"[Qualcomm, Intel India, Nvidia GPU Ventures, H...",246,63,0,17,0,False,0.07193,0.00001,"[Cognizant, Infosys, Tata Consultancy Services...",7,0,5

In [183]:
print(Table['Category_Number'].value_counts())

0    33693
1    24362
2     1427
3      280
4      216
5       69
6       38
7       30
9        7
8        4
Name: Category_Number, dtype: int64

##### HERE 'Category_Number' = '0' represents the companies which don't come under any category mentioned which implies that the number of employes data is missing or have no value

In [184]:
Table=Table.reset_index()
#df = df.drop('column_name', axis=1)
Table=Table.drop('index',axis=1)
Table.head()

,Company uuid,Company Name,Employees Count,List of companies they hired from,Employee count they hired,List of companies their ex-employees work,Employee count their ex-employees work,IIT Count,IIT Fresher Count,NIT Count,NIT Fresher Count,Is score calculated,Tier-1 College Density Score,Tier1 College Freshers Density Score,List of companies where hiring companies hire from,Category_Number,Tier-1 College Freshers Strength,Tier-1 College Strength
0,None,altran technologies india pvt ltd,1,[L&T Technology Services Ltd.],1,NaN,0,0,0,0,0,False,0.00001,0.00001,"[HCL Technologies, Tech Mahindra, Wipro Techno...",1,0,0
1,,L&T Technology Services Ltd.,6890,"[HCL Technologies, Tech Mahindra, Wipro Techno...",4019,[Robert Bosch Engineering & Business Solutions...,2192,16,7,13,3,True,0.004499,0.00464,"[Wipro Technologies, Tata Consultancy Services...",8,0,0
2,fbd567c5e7395b46974ece634a19ff2e,Amdocs,1711,"[Tata Consultancy Services, Infosys, Cognizant...",1614,"[Tata Consultancy Services, Accenture, Tech Ma...",733,4,0,5,1,False,0.00526,0.035714,"[Cognizant, Infosys, Wipro Technologies, Accen...",7,0,0
3,7aa9a32dd8f27a05646e7317af05959b,Xperia,6,"[Ultra-Scan Corporation, Telescope Services AB...",6,[Cisco],1,0,0,0,0,False,0.00001,0.00001,"[Wipro Technologies, Tata Consultancy Services...",1,0,0
4,,Ultra-Scan Corporation,1140,"[Wipro Technologies, Tata Consultancy Services...",1102,"[Qualcomm, Intel India, Nvidia GPU Ventures, H...",246,63,0,17,0,False,0.07193,0.00001,"[Cognizant, Infosys, Tata Consultancy Services...",7,0,5

In [185]:
Table.head()

,Company uuid,Company Name,Employees Count,List of companies they hired from,Employee count they hired,List of companies their ex-employees work,Employee count their ex-employees work,IIT Count,IIT Fresher Count,NIT Count,NIT Fresher Count,Is score calculated,Tier-1 College Density Score,Tier1 College Freshers Density Score,List of companies where hiring companies hire from,Category_Number,Tier-1 College Freshers Strength,Tier-1 College Strength
0,None,altran technologies india pvt ltd,1,[L&T Technology Services Ltd.],1,NaN,0,0,0,0,0,False,0.00001,0.00001,"[HCL Technologies, Tech Mahindra, Wipro Techno...",1,0,0
1,,L&T Technology Services Ltd.,6890,"[HCL Technologies, Tech Mahindra, Wipro Techno...",4019,[Robert Bosch Engineering & Business Solutions...,2192,16,7,13,3,True,0.004499,0.00464,"[Wipro Technologies, Tata Consultancy Services...",8,0,0
2,fbd567c5e7395b46974ece634a19ff2e,Amdocs,1711,"[Tata Consultancy Services, Infosys, Cognizant...",1614,"[Tata Consultancy Services, Accenture, Tech Ma...",733,4,0,5,1,False,0.00526,0.035714,"[Cognizant, Infosys, Wipro Technologies, Accen...",7,0,0
3,7aa9a32dd8f27a05646e7317af05959b,Xperia,6,"[Ultra-Scan Corporation, Telescope Services AB...",6,[Cisco],1,0,0,0,0,False,0.00001,0.00001,"[Wipro Technologies, Tata Consultancy Services...",1,0,0
4,,Ultra-Scan Corporation,1140,"[Wipro Technologies, Tata Consultancy Services...",1102,"[Qualcomm, Intel India, Nvidia GPU Ventures, H...",246,63,0,17,0,False,0.07193,0.00001,"[Cognizant, Infosys, Tata Consultancy Services...",7,0,5

#  Save the data category wise into separate excel sheet and name it as category_k.xlsx where k is the category number

In [186]:
#df1[df1["A"] > 0.5]
category_1=Table[Table["Category_Number"] == 1]
category_2=Table[Table["Category_Number"] == 2]
category_3=Table[Table["Category_Number"] == 3]
category_4=Table[Table["Category_Number"] == 4]
category_5=Table[Table["Category_Number"] == 5]
category_6=Table[Table["Category_Number"] == 6]
category_7=Table[Table["Category_Number"] == 7]
category_8=Table[Table["Category_Number"] == 8]
category_9=Table[Table["Category_Number"] == 9]
category_0=Table[Table["Category_Number"] == 0]

In [187]:
category_1.to_excel('category_1.xlsx')
category_2.to_excel('category_2.xlsx')
category_3.to_excel('category_3.xlsx')
category_4.to_excel('category_4.xlsx')
category_5.to_excel('category_5.xlsx')
category_6.to_excel('category_6.xlsx')
category_7.to_excel('category_7.xlsx')
category_8.to_excel('category_8.xlsx')
category_9.to_excel('category_9.xlsx')
category_0.to_excel('category_0.xlsx')